Repository Shanghai-Squad/MovieApp, pull requests merged in 2025-09, with the labels that each got.

#2 refactor/fab-add-button
  app/src/main/res/drawable/add_icon.xml
  app/src/main/res/layout/fragment_my_lists.xml
  app/src/main/res/values/themes.xml
Labels: refactor

#92 fix: biography actor details
  app/src/main/res/layout/fragment_actor_details.xml
Labels: bug

#119 fix/image-view-filtter-issues
  ImageHaramBlur/src/main/java/com/ae/imageharamblur/ImageModerationProcessor.kt
  ImageHaramBlur/src/main/java/com/ae/imageharamblur/models/GenderDetectionModel.kt
  ImageHaramBlur/src/main/java/com/ae/imageharamblur/ui/ImageModerationController.kt
  ImageHaramBlur/src/main/java/com/ae/imageharamblur/ui/ImageViewFilter.kt
  ImageHaramBlur/src/main/java/com/ae/imageharamblur/ui/ModerationCacheManager.kt
  ImageHaramBlur/src/main/res/layout/view_image_filter.xml
Labels: bug, enhancement

#28 refactor/login-signup-screen
  app/src/main/java/com/karrar/movieapp/ui/login/LoginFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/login/LoginViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/login/signup/SignUpDialog.kt
  app/src/main/java/com/karrar/movieapp/ui/login/signup/SignUpEvents.kt
  app/src/main/java/com/karrar/movieapp/ui/login/signup/SignUpViewModel.kt
  app/src/main/res/color/button_state_primary.xml
  app/src/main/res/color/button_state_secondary.xml
  app/src/main/res/color/text_input_stroke_selector.xml
  app/src/main/res/drawable/bottom_sheet_scrim.xml
  app/src/main/res/drawable/cineverse_bottom_sheet_background.xml
  app/src/main/res/drawable/cineverse_password_toggle.xml
  app/src/main/res/drawable/password_toggle_selector.xml
  app/src/main/res/drawable/text_cursor.xml
  app/src/main/res/layout/dialog_sign_up.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: refactor

#135 fix: display same movies in match screen
  app/src/main/java/com/karrar/movieapp/data/repository/MovieRepositoryImp.kt
Labels: bug

#130 fix onboarding card size and remove app name
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/themes.xml
Labels: refactor

#149 feat: Enable auto-update for PRs from develop
  .github/workflows/on_pull_request_android.yml
  .github/workflows/on_pull_request_android_ios.yml
Labels: enhancement

#157 fix/cast-details-issue
  app/src/main/java/com/karrar/movieapp/domain/mappers/actor/ActorSocialMediaMapper.kt
  app/src/main/res/layout/fragment_actor_details.xml
Labels: bug

#164 fix trial not working in movie details
  app/build.gradle
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/layout/activity_youtube_player.xml
Labels: bug

#199 fix(cast_details): UI adjustments and string update
  app/src/main/res/drawable/rounded_pill_background.xml
  app/src/main/res/layout/fragment_actor_details.xml
  app/src/main/res/layout/item_movie_actor.xml
  app/src/main/res/layout/item_social.xml
  app/src/main/res/values/strings.xml
Labels: bug

#194 refactor/see-more-seasons
  app/src/main/java/com/karrar/movieapp/domain/mappers/series/SeasonMapper.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/tvShowDetails/GetTvShowDetailsUseCase.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/DetailIntractionListener.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/MovieDetailsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/DetailUIStateAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/TvShowDetailsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/TvShowDetailsUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/TvShowDetailsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/seasons/SeasonFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/seasons/SeasonViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/seasons/SeasonsUiEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/tvShowDetails/seasons/ShowAllSeasonsAdapterUIState.kt
  app/src/main/res/layout/fragment_season.xml
  app/src/main/res/layout/item_see_all_season.xml
  app/src/main/res/layout/list_season.xml
  app/src/main/res/navigation/movie_navigation.xml
Labels: refactor
